package de.kauker.unofficial

const val GOOGLE_PLAY_VERSION = true

const val DURATION_TRANSACTION_SYNC_TIMEOUT = 10 * 1000
const val DURATION_MIN_TRANSACTION_AGE_FOR_SYNC = 15 * 1000
const val DURATION_MAX_TRANSACTION_AGE = 7 * 24 * 60 * 60 * 1000

const val LIMIT_MAX_TRANSACTION_COUNT = 100
