package de.kauker.unofficial

const val GOOGLE_PLAY_VERSION = false

const val GROCY_PREDEFINED_API_URL = ""
const val GROCY_PREDEFINED_API_TOKEN = ""

val GROCY_SUPPORTED_VERSIONS = listOf(
    "4.0.0", "4.0.1", "4.0.2", "4.0.3", "4.1.0"
)

const val DURATION_TRANSACTION_SYNC_TIMEOUT = 10 * 1000
const val DURATION_MIN_TRANSACTION_AGE_FOR_SYNC = 15 * 1000
const val DURATION_MAX_TRANSACTION_AGE = 7 * 24 * 60 * 60 * 1000

const val LIMIT_MAX_TRANSACTION_COUNT = 100
